# steps:
#   - name: 'alpine'  # Using a lightweight Docker image
#     entrypoint: 'echo'
#     args: 
#       - 'Hello, World!'
# logsBucket: 'gs://trigger-exp-dt-bucket'

steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        echo "hello world"
        date
        hostname
    entrypoint: bash
service_account: cloudbuild-sa@trigger-exp-id.iam.gserviceaccount.com
logsBucket: 'gs://trigger-exp-dt-bucket'
